# Generated by Django 5.1.7 on 2025-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemes_urbains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_problemes/'),
        ),
    ]
